import { dirname } from "path";
import { fileURLToPath } from "url";

import { FlatCompat } from "@eslint/eslintrc";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import importPlugin from "eslint-plugin-import";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

// Try to extend Next.js configs, fallback to minimal config if circular reference occurs
let nextConfigs = [];
let hasNextConfigs = false;
try {
  nextConfigs = compat.extends("next/core-web-vitals", "next/typescript") || [];
  hasNextConfigs = nextConfigs.length > 0;
} catch (error) {
  // If circular reference error, use minimal config
  console.warn("ESLint: Could not load Next.js configs, using minimal config");
}

const eslintConfig = [
  {
    ignores: [
      ".next/**/*",
      "node_modules/**/*",
      "dist/**/*",
      "build/**/*",
      "coverage/**/*",
      "*.config.js",
      "*.config.ts",
      "next.config.*",
      "postcss.config.*",
      "tailwind.config.*",
      "next-env.d.ts", // Auto-generated by Next.js
      "scripts/**/*.js", // Scripts are plain JS, not TypeScript
    ],
  },
  ...nextConfigs,
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
        project: "./tsconfig.json",
        tsconfigRootDir: __dirname,
      },
    },
    plugins: {
      "@typescript-eslint": typescriptEslint,
      react: react,
      "react-hooks": reactHooks,
      import: importPlugin,
    },
    settings: {
      "import/resolver": {
        // Use node resolver as primary - it's more reliable and handles Windows paths better
        node: {
          extensions: [".js", ".jsx", ".ts", ".tsx", ".json"],
        },
        // TypeScript resolver is disabled to avoid path resolution issues on Windows
        // TypeScript compiler handles type checking, ESLint just needs module resolution
        // Path aliases (@/*) are handled by Next.js and TypeScript compiler
      },
      "import/ignore": ["\\.(css|scss|sass|less)$"],
    },
    rules: {
      // TypeScript-specific rules
      "@typescript-eslint/no-unused-vars": hasNextConfigs
        ? "off"
        : [
            "error",
            {
              argsIgnorePattern: "^_",
              varsIgnorePattern: "^_",
              destructuredArrayIgnorePattern: "^_",
              caughtErrorsIgnorePattern: "^_",
            },
          ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-expressions": "error",
      "@typescript-eslint/no-inferrable-types": "warn",
      "@typescript-eslint/no-var-requires": "error",

      // React-specific rules
      "react-hooks/exhaustive-deps": "error",
      "react/jsx-key": "error",
      "react/no-unescaped-entities": "warn",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-undef": "error",
      "react/no-array-index-key": "error",
      "react/self-closing-comp": "error",
      "react/jsx-curly-brace-presence": [
        "error",
        { props: "never", children: "never" },
      ],

      // Import rules
      "import/no-unresolved": [
        "warn", // Changed to warn instead of error to avoid false positives
        {
          ignore: [
            "^@/",
            "^@krapi/",
            "^@smartsamurai/",
            "^react-resizable-panels",
            "^next/",
            "^\\.",
          ],
          // Don't fail on TypeScript type-only imports
          caseSensitive: true,
        },
      ],
      "import/no-cycle": "off",
      "import/no-unused-modules": "off",
      "import/order": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
          ],
          "newlines-between": "always",
          alphabetize: { order: "asc" },
        },
      ],
      "import/no-duplicates": "error",
      "import/no-named-as-default": "warn",
      "import/no-named-as-default-member": "warn",
      "import/no-default-export": "off",

      // General rules
      "no-console": "warn",
      "prefer-const": "error",
      "no-var": "error",
      "no-unused-vars": "off",
      "no-warning-comments": "warn",
      "prefer-template": "error",
      "object-shorthand": "error",
      "prefer-arrow-callback": "error",
      "no-useless-return": "error",
      "no-useless-constructor": "error",
      "no-duplicate-imports": "error",
    },
  },
];

export default eslintConfig;
